name: ci-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: ["lts", "canary"]

    steps:
      - uses: actions/checkout@v7

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: lint
        run: deno lint

      - name: test
        run: deno test --allow-all

      - name: audit
        run: deno audit
